setup:
  # Whether to prompt for SESSION_ID
  prompt_session_id: true

  # Name for the BOT
  bot_name: levanter

# System package setup
system_packages:
  - git
  - ffmpeg
  - curl

# Node.js setup
node_setup:
  install: true
  version: 16

# Yarn setup
yarn_setup:
  install: true

# PM2 setup
pm2_setup:
  install: true

# Bot installation
bot_installation:
  repository: https://github.com/lyfe00011/whatsapp-bot-md
  directory: levanter
  config:
    prefix: "."
    sticker_packname: LyFE
    always_online: false
    rmbg_key: null
    language: en
    warn_limit: 3
    force_logout: false
    brainshop: "159501,6pq8dPiYt7PdqHz3"
    max_upload: 60
    reject_call: false
    sudo: 989876543210
    tz: Asia/Kolkata
    vps: true
    auto_status_view: true
    send_read: true
    ajoin: true
    session_id: 16_2_177b_e587_3993 # Will be populated if provided
